---
- hosts: 172.31.1.212
  become: yes
  tasks:
   - include_tasks: myfile.yml
   
   - name: install webserver
     apt:
      name : apache2
  
   - name: copy file into ansible node side
     copy:
      src: staticfile.txt
      dest: /home/ubuntu/mystaticfile.txt

   - name: copy index.j2 file into ansible node side
     template:
      src: index.j2
      dest: /var/www/html/index.html
     notify:  restartwebserver
   
   - name: download internet file
     get_url:
      url: https://get.jenkins.io/war-stable/2.375.1/jenkins.war
      dest: /home/ubuntu/jenkins.war
      force_basic_auth: yes 
     notify:  restartwebserver
  
  handlers:
  - name: restartwebserver
    service:
      name: apache2
      state: restarted
