---
- hosts: 172.31.1.212
  become: yes
  tasks:
   - include_tasks: myfile.yml
   
   - name: install git
     apt:
      name : git
  
   - name: copy file into ansible node side
     copy:
      src: staticfile.txt
      dest: /home/ubuntu/mystaticfile.txt